apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:zbnO9kB40swnJXmbBRonvbRdJvood4nigMRMvs5YMeCMYd0Z,iv:TCieuxzPNJQ13fPPhsN5B7Une1o2k/6wrYSMx6kOxgU=,tag:7TnABAB5eowpZwnGAe33TQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:E2410YXbtSueB0A1g6E/GymQcr6vxJB44SM9zjt4vuvCtQ+/+fhb4gwSLnW0BRXJoGjvxmQsP4df1uyNRr2erzYn7WFMNNwURYIkq8VmMVlvjS2ydmgO/lKJwv6CVB64hKIoy2EGkoTbDYZ/bzWZqqanJrnGj+y9G6o+x8RaPe9Q+RhnfC0g0eQeAqdEqyVAPd7BY+Fg7knQqXFoZSZVAfwceeXjs0ctarmbqG4XWw==,iv:RPDBKEeoo11DtZLj+Z7cEyM6QwkSWGCbfQW5fdAXfi4=,tag:R12MdkCovmRa90h9uAXPIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18myfuh64egh54f4kkcl4cyk9ul4uql2hst4cpnst0h6p240h6u7suh3cmf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aEQ1VnowWVE0cXhSMG5N
            RVY1YmljWGRaaVY2SFVaRm9tdVJnY0U4VHpBCjVqRGVzQW03V0d0bUwvZ2lhN1BP
            M0p5YkZrQTh0cWtqcXNqSUNqeXAreXcKLS0tIFU0KzkrUmIvSUQ3VjVYajdzV1BZ
            VkR1QkhkdnhvOWUwVVd6bXhadFk1TWMKD2HPD3jHL1+m7HaW+7g5ESJAYWxZE9CT
            vcpLpM32CVEmeUASs3zMfr2l4AFXFpEoCc3vVrkaj/awzvumItE++w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T05:13:27Z"
    mac: ENC[AES256_GCM,data:7ygts836PqLE/U8Tzd9eUhzM9LWDMd0dY/cYa9G5HNF/vvhTUsBXBHSEec4ddJKXMU3EMaFbTvKKPNct3fxYvFNrQCQevVVdeXXNXIyMbOzjwZEJ2tA8zEex/SDm4wIuPWyClJZoV0KEp6zbTGmrfOWNaavG0Vk5xKZb/TgXvb4=,iv:VZ9Nw5fQpkkOcqUB+dzyJvyTPdGoRjh7uj+AEBtqNuY=,tag:lywPgwuxakjIPl7FJDsFhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
