apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:U4TdYkZIoBd0UcWDl9mCXdfIzVUJEMOluFMgz4FIs2ev1JF/4c4jtg==,iv:H3RzMlwJuLR+3CYfT06eHQtHnMKdRoHj37iGyq1Rkdk=,tag:BrepQduo8Iv+0btluG6iHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18myfuh64egh54f4kkcl4cyk9ul4uql2hst4cpnst0h6p240h6u7suh3cmf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRDl6T0ZXYnFHWjhQRlJY
            Y3FLZ2NteG8wNFU2U3B2SXhKTXpZMGJtQ1NZCnUxOEpaMGxwMzliUVFQN211L3lQ
            UkhDOXJoY0JwTm1FelNvYk1SOFdKUFUKLS0tIDFINWJNWXFicDd0WTI2QXN2OGhG
            OEhhYU85bzA5NFNsakxBeXNhQ1MxT1EKmecYeOrfcTpqlbPIDIus+tfcxs8d3qcJ
            6meoleS+VQiFAJQoppLHmwVZrrdXKiwbCjuDw6LGUPFBSuMQYjyKjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T02:20:20Z"
    mac: ENC[AES256_GCM,data:9fsdZUcm+v4Df7+tmi70o9snSaxoOUn5HxQBftTIZw22JKISIZxiT5WEyYfbR8ev3JC+52F2C+cuvFGRdC9WZ2+7apRENk5m8Xjs3g7nOed7qhaYGZuDrXwloXdu5hqKv3UETqIFomUZdPMQEAKr7UyLq1pMUs++FA58/oRH9w0=,iv:llgKhsdrxQWBo2HVcfju3ztmqERS919gZXMpf/2d/BA=,tag:8bCja7nCDiDR9fOFekqYhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
