apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:aJTy+uaIUoHus52BFdn+qIhf89+XFj1VJnJogJlT3AQ=,iv:57aSy6COtCszc8jZX5kJ+fivq604N39OkvfUF2AI70I=,tag:JQdG8UHWQduCe7Zx9F6IkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18myfuh64egh54f4kkcl4cyk9ul4uql2hst4cpnst0h6p240h6u7suh3cmf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMWtvVkRLeGh0RE5SNHBr
            QUFZRTZPaWFtUllCQ0NQQ21MRUhmTzRDRVVrCk05UHF1d0NlMHlWRlhlQ3h5em5Q
            Y1hjdUZldXhMbG9iUnVGL0xrcElmVmMKLS0tIExrUGt0dkFPNGlwd1dhdkQrYW1L
            VGU4VmJtcG9ZQ0d0dlA4K2Q3L00vTmMKy6VflefnGUu2VC/qNYP0FI+ZPmT+dwIx
            8xhW0oumui3rcR3Myv7NJdARVFLjarOGepqDKnikeiJNbjegJIKcfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T17:21:53Z"
    mac: ENC[AES256_GCM,data:JP5gyypmWOyYNKI6Nj8CxuEJzEBCeK7RaMjOlXZm04T1ZW8IZpuK+Ojj4ROiFcspJcRxGh62mob9MEZzDBViJd0PmOpHsAdw2MJcZleDSPtmw6mVJGIfWgXIeHl+4MxCCL04IsMgknBJ1sqYX3Ky/Vshh5eyXP7RKrt2gA2wapg=,iv:sCvlegK1KRRiv+QBXQYiTlkD68jvK63y9zLCASsWN8g=,tag:q8N7gnXA65MJnty6ca6zlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
